---
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/pantheon-systems/redshirt-cli-wrapper

    steps:
      - checkout
      # NOTE: run 'deps' instead of 'deps-circle'. We don't need the go install script when using circleci 2.0
      - run: make deps
      - run: make test-circle
      - run: make build-circle
      - deploy:
          name: github_release
          tag: /(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)/
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              mv redshirt-cli-wrapper "$CIRCLE_ARTIFACTS"/
              go get github.com/tcnksm/ghr
              ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` "$CIRCLE_ARTIFACTS"/
            fi
